name: Publish to github repo

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package release version'
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify source:jar deploy -P ex-integration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}