# DISABLED: This workflow conflicts with proper semantic versioning
# Use the manual release.yml workflow for proper releases instead
name: Deploying based on release (DISABLED)
on:
  workflow_dispatch: # Changed from pull_request to manual trigger only

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
  build:
    needs: if_merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'
      - name: Building the app
        run: mvn --batch-mode --file pom.xml --update-snapshots package -P ex-integration
      #      - run: mkdir staging && cp target/*.jar staging
      #      - uses: actions/upload-artifact@v2
      #        with:
      #          name: Package
      #          path: staging
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up corretto JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{github.run_number}}
          release_name: Release V${{github.run_number}}

      - name: Update version
        run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false

      - name: Publish to GitHub Packages Apache Maven
        run: mvn -B deploy -DskipTests --file pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}